# -*- coding: utf-8 -*-
"""crawling1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jq8NsG4vzzZDkEOoMCez6hMd2939rv51
"""

from urllib.request import urlopen
from bs4 import BeautifulSoup as bs

url="http://www.cgv.co.kr/movies/?lt=1&ft=0"
html=urlopen(url).read()


soup=bs(html, "lxml")

movies=soup.find_all("strong", attrs={"class":"title"})
print("<무비차트>----예매율 순")
k=[]
for movie in movies :
  k.append(movie.get_text('\n'))
for i in range(1, 20) :
  print(i, k[i-1])